version: "1.0"

services:
  app:
    container_name: order-microservice
    command: java -jar target/order-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    depends_on:
      - database-order
    volumes:
      - ./:/app/app
    links:
      - database-order
    networks:
      - internal
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

  database-order:
    image: postgres
    container_name: database-order
    expose:
      - "5435"
    ports:
      - "5435:5435"
    volumes:
      - ./:/app/
    command: -p 5435
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=order_db
    networks:
      - internal

networks:
  internal:
    name: internal